# These are supported funding model platforms

github: [JDsnyke]
# Open Collective: opencollective
# Ko-fi: kofi
# Tidelift: tidelift
# Community Bridge: community_bridge
# Liberapay: liberapay
# IssueHunt: issuehunt
# Otechie: otechie
# Custom: custom

# Custom funding link
# custom: ['https://www.patreon.com/my_username', 'https://donations.example.com'] 